<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinanceTracker.Web.Contracts\FinanceTracker.Web.Contracts.csproj" />
	</ItemGroup>

</Project>
